# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='position',
            new_name='D',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='duties',
            new_name='ob',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='organization',
            new_name='plaсe',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='site',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='work',
            name='region',
        ),
        migrations.AlterField(
            model_name='work',
            name='period',
            field=models.TextField(verbose_name='Периуд работы'),
        ),
    ]
