# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 19:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20161102_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='period',
            new_name='time',
        ),
    ]
