# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import datetime

class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20161102_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(max_length=32, verbose_name='Организация')),
                ('url', models.CharField(blank=True, max_length=64, verbose_name='Сайт')),
                ('sp', models.CharField(max_length=32, verbose_name='Специальность')),
                ('Data', models.CharField(max_length=16, verbose_name='Год обучения')),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Организация')),
                ('url', models.CharField(max_length=32, verbose_name='Картинка')),
            ],
        ),
        migrations.CreateModel(
            name='StPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Университет')),
                ('url', models.CharField(blank=True, max_length=64, verbose_name='Сайт')),
                ('sp', models.CharField(max_length=32, verbose_name='Специальность')),
                ('Level', models.CharField(max_length=16, verbose_name='Уровень образования')),
                ('dip', models.CharField(max_length=32, verbose_name='Тема выпускной работы')),
                ('time_st', models.DateField(verbose_name='Начало обучения')),
                ('time_end', models.DateField(verbose_name='Конец обучения')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_pi', models.CharField(max_length=32, verbose_name='Иконка')),
                ('url_text', models.CharField(blank=True, max_length=64, verbose_name='Задача')),
                ('url_sov', models.CharField(max_length=64, verbose_name='Решение')),
                ('category', models.CharField(max_length=16, verbose_name='Тип задачи')),
            ],
        ),
        migrations.RenameField(
            model_name='work',
            old_name='plaсe',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='work',
            name='time',
        ),
        migrations.AddField(
            model_name='work',
            name='time_end',
            field=models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Конец работы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='time_st',
            field=models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Начало работы'),
            preserve_default=False,
        ),
    ]
