# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20161105_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stplace',
            name='time_end',
            field=models.CharField(max_length=32, verbose_name='Конец обучения'),
        ),
        migrations.AlterField(
            model_name='stplace',
            name='time_st',
            field=models.CharField(max_length=32, verbose_name='Начало обучения'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_end',
            field=models.CharField(max_length=32, verbose_name='Конец работы'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_st',
            field=models.CharField(max_length=32, verbose_name='Начало работы'),
        ),
    ]
