# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20161105_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Data',
            field=models.CharField(blank=True, max_length=16, verbose_name='Год обучения'),
        ),
        migrations.AlterField(
            model_name='course',
            name='org',
            field=models.CharField(blank=True, max_length=32, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='course',
            name='sp',
            field=models.CharField(blank=True, max_length=32, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='name',
            field=models.CharField(blank=True, max_length=32, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='url',
            field=models.CharField(blank=True, max_length=32, verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='stplace',
            name='Level',
            field=models.CharField(blank=True, max_length=16, verbose_name='Уровень образования'),
        ),
        migrations.AlterField(
            model_name='stplace',
            name='dip',
            field=models.CharField(blank=True, max_length=32, verbose_name='Тема выпускной работы'),
        ),
        migrations.AlterField(
            model_name='stplace',
            name='name',
            field=models.CharField(blank=True, max_length=32, verbose_name='Университет'),
        ),
        migrations.AlterField(
            model_name='stplace',
            name='sp',
            field=models.CharField(blank=True, max_length=32, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='stplace',
            name='time_end',
            field=models.CharField(blank=True, max_length=32, verbose_name='Конец обучения'),
        ),
        migrations.AlterField(
            model_name='stplace',
            name='time_st',
            field=models.CharField(blank=True, max_length=32, verbose_name='Начало обучения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, max_length=16, verbose_name='Тип задачи'),
        ),
        migrations.AlterField(
            model_name='task',
            name='url_pi',
            field=models.CharField(blank=True, max_length=32, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='task',
            name='url_sov',
            field=models.CharField(blank=True, max_length=64, verbose_name='Решение'),
        ),
        migrations.AlterField(
            model_name='work',
            name='D',
            field=models.CharField(blank=True, max_length=16, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(blank=True, max_length=32, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_end',
            field=models.CharField(blank=True, max_length=32, verbose_name='Конец работы'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_st',
            field=models.CharField(blank=True, max_length=32, verbose_name='Начало работы'),
        ),
    ]
