# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-05 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20161105_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Хобби'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='url',
            field=models.CharField(max_length=32, verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='stplace',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Университет'),
        ),
        migrations.AlterField(
            model_name='stplace',
            name='sp',
            field=models.CharField(max_length=32, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='stplace',
            name='time_end',
            field=models.DateField(max_length=32, verbose_name='Конец обучения'),
        ),
        migrations.AlterField(
            model_name='stplace',
            name='time_st',
            field=models.DateField(max_length=32, verbose_name='Начало обучения'),
        ),
        migrations.AlterField(
            model_name='stplace',
            name='url',
            field=models.CharField(max_length=64, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='work',
            name='D',
            field=models.CharField(max_length=16, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='work',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_end',
            field=models.DateField(blank=True, max_length=32, verbose_name='Конец работы'),
        ),
        migrations.AlterField(
            model_name='work',
            name='time_st',
            field=models.DateField(blank=True, max_length=32, verbose_name='Начало работы'),
        ),
    ]
