# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-05 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20161105_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='Название')),
                ('region', models.CharField(blank=True, max_length=32, verbose_name='Регион')),
                ('url', models.CharField(blank=True, max_length=64, verbose_name='Сайт')),
                ('activity', models.TextField(blank=True, verbose_name='Сфера деятельности')),
            ],
        ),
        migrations.RemoveField(
            model_name='work',
            name='name',
        ),
        migrations.RemoveField(
            model_name='work',
            name='url',
        ),
        migrations.AddField(
            model_name='work',
            name='organization',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Organization', verbose_name='Организация'),
            preserve_default=False,
        ),
    ]
